name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Next Build
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
      - name: Install Dependencies
        run: bun ci
      - name: Build
        run: bun run build
